services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb-practica
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: practica
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario
    ports:
      - "3306:3306"
    volumes:
      - datos_mariadb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  datos_mariadb: